name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"] 

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Download and setup Spark 3.5.1
      run: |
        wget https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz
        tar xzf spark-3.5.1-bin-hadoop3.tgz
        sudo mv spark-3.5.1-bin-hadoop3 /opt/spark
        echo "SPARK_HOME=/opt/spark" >> $GITHUB_ENV
        echo "/opt/spark/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pyspark==3.5.1 pandas pyarrow
        pip install -e .
    
    - name: Run pytest
      run: |
        pytest tests/ --verbose